stages:
  - test
  - build
  - deploy

variables:
  RUST_BACKTRACE: "1"
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  key: $CI_BUILD_STAGE-$CI_BUILD_REF_NAME
  paths:
    - $HOME/.cargo
    - cargo/
    - target/
  

.install_libsodium_template: &install_libsodium
  - curl --location --output libsodium18_1.0.13-1_amd64.deb http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium18_1.0.13-1_amd64.deb
  - curl --location --output libsodium-dev_1.0.13-1_amd64.deb http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium-dev_1.0.13-1_amd64.deb
  - sudo dpkg -i libsodium-dev_1.0.13-1_amd64.deb libsodium18_1.0.13-1_amd64.deb

.cargo_build_template: &cargo_build
  stage: build
  before_script: *install_libsodium
  script:
    - cargo test --verbose --jobs 1
    - cargo build --verbose --jobs 1
    - cargo doc
  artifacts:
    paths:
    - target/debug
    - target/doc
    name: "${CI_JOB_STAGE}-${CI_BUILD_NAME}"
    expire_in: 1 week
  tags:
    - docker
    - linux
  only:
    - master
  except:
    - /test.*/

# linux start
1.21.0:tox:
  image: rustdocker/rust:1.21.0
  <<: *cargo_build

stable:tox:
  image: rustdocker/rust:stable
  <<: *cargo_build

beta:tox:
  image: rustdocker/rust:beta
  <<: *cargo_build

nightly:tox:
  image: rustdocker/rust:nightly
  <<: *cargo_build

### linux end

### windows start 

### windows end

### osx start 

### osx end
