language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

branches:
  except:
    - test

notifications:
  irc:
    channels: "chat.freenode.net#zetox"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
    on_success: change
    skip_join: true

matrix:
  allow_failure:
  - rust: nightly
  - branches: travis

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./bootstrap-ubuntu-14-04.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./bootstrap-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH ; fi
