[package]
name = "tox"
version = "0.0.1"
authors = ["Zetok Zalbavar <zetok@openmailbox.org>"]


[dependencies]
clippy = { version = "*", optional = true }
log = "0.3"
sodiumoxide = "0.0.12"
mio = { git = "https://github.com/carllerche/mio", rev = "bf5de4d51ee00f140c4fcbd73b4d53717a3ac9e3" }

[dev-dependencies]
quickcheck = "0.2"
rand = "0.3"
regex = "0.1"
rustc-serialize = "0.3"
