[package]
name = "tox"
version = "0.0.1"
authors = ["Zetok Zalbavar <zetok@openmailbox.org>"]

[dependencies.sodiumoxide]
git = "https://github.com/dnaq/sodiumoxide.git"

[dependencies]
ip = "1.1"
log = "0.3"

[dev-dependencies]
quickcheck = "0.2"
rustc-serialize = "0.3"
