[package]
name = "tox"
version = "0.0.1"
authors = ["Zetok Zalbavar <zetok@openmailbox.org>"]


[dependencies]
clippy = { version = "*", optional = true }
log = "0.3"
sodiumoxide = "0.0.10"

[dev-dependencies]
quickcheck = "0.2"
rustc-serialize = "0.3"
