[package]
name = "tox"
version = "0.0.1"
authors = ["Zetok Zalbavar <zetok@openmailbox.org>"]

[dependencies.sodiumoxide]
git = "https://github.com/dnaq/sodiumoxide.git"

[dependencies]
libsodium-sys = "0.0.9"
ip = "1.1"

[dev-dependencies]
quickcheck = "0.2"
